### ISSUE TITLE
model property name must be 'mongules'

### ISSUE THREAD

**Issue by MickCrozier** [ricardofbarros/mongules#2]
Hi Ricardo.

Just having a play - and discovered that when including in the schema it has to be named 'mongules'. Whereas I was looking to include it my model definition as 'validator' - I guess something more obvious to someone else looking in on definition.

**Comment by ricardofbarros** [comment]
I changed from `mongules` to `validator` as well and if you inspect the code you'll see it's easier to read and understand the code now. :)
